import io
import json
import unittest
from unittest.mock import MagicMock, patch

from core.models import AutoCompleteData
from services.gemini_service import GeminiCompletionService


class TestGeminiCompletionService(unittest.TestCase):

    def test_missing_api_key_raises_error(self):
        service = GeminiCompletionService(api_key=None)
        with patch.dict("os.environ", {}, clear=True):
            with self.assertRaises(ValueError):
                service.generate_completions("hello")

    @patch("urllib.request.urlopen")
    def test_successful_completions_generation(self, mock_urlopen):
        fake_api_response = {
            "candidates": [
                {
                    "content": {
                        "parts": [
                            {
                                "text": json.dumps([
                                    "hello world this is an AI completion",
                                    "hello there how can I assist you today",
                                ])
                            }
                        ]
                    }
                }
            ]
        }
        mock_response = MagicMock()
        mock_response.read.return_value = json.dumps(fake_api_response).encode("utf-8")
        mock_response.__enter__.return_value = mock_response
        mock_urlopen.return_value = mock_response

        service = GeminiCompletionService(api_key="fake-test-key")
        results = service.generate_completions("hello", domain_context="General", top_k=2)

        self.assertEqual(len(results), 2)
        self.assertIsInstance(results[0], AutoCompleteData)
        self.assertEqual(results[0].completed_sentence, "hello world this is an AI completion")
        self.assertEqual(results[0].source_text, "[Generated by Gemini]")
        self.assertEqual(results[0].offset, 0)
        self.assertEqual(results[0].score, 0)

    def test_empty_query_returns_empty_list(self):
        service = GeminiCompletionService(api_key="fake-test-key")
        results = service.generate_completions("")
        self.assertEqual(results, [])


if __name__ == "__main__":
    unittest.main()