"""Interactive CLI loop for the Sentence Autocomplete Engine with AI Mode."""

import os
import sys
from typing import List, Optional

from core.models import AutoCompleteData
from core.normalizer import normalize_text
from core.indexer import DataManager
from core.scoring import rank_candidates
import core.search_engine as search_engine
from services.gemini_service import GeminiCompletionService

RESET_TOKEN = "#"

manager = DataManager()
gemini_service = GeminiCompletionService()

# Modes: 'local' (Part A corpus matching) or 'ai' (Part B Gemini context generator)
CURRENT_MODE = "local"
AI_CONTEXT = "General"


def format_result(rank: int, result: AutoCompleteData) -> str:
    if result.source_text == "[Generated by Gemini]":
        return f"{rank}. {result.completed_sentence}  \033[94m[AI Generated: Gemini]\033[0m"
    return (
        f"{rank}. {result.completed_sentence}"
        f"  [source: {result.source_text}, line {result.offset}, score: {result.score}]"
    )


def handle_local_query(query: str) -> None:
    normalized_query = normalize_text(query)
    matches = search_engine.search(query, manager) if hasattr(search_engine, "search") else []
    results = rank_candidates(normalized_query, matches, manager.get_sentence)

    if not results:
        print("No matching sentences found in corpus.")
        return

    for rank, result in enumerate(results, start=1):
        print(format_result(rank, result))


def handle_ai_query(query: str) -> None:
    try:
        results = gemini_service.generate_completions(query, domain_context=AI_CONTEXT, top_k=5)
        if not results:
            print("No AI completions generated.")
            return

        for rank, result in enumerate(results, start=1):
            print(format_result(rank, result))
    except Exception as err:
        print(f"\033[91m[Gemini API Error: {err}]\033[0m")
        print("Falling back to standard local corpus search...")
        handle_local_query(query)


def handle_query(query: str) -> None:
    if CURRENT_MODE == "ai":
        handle_ai_query(query)
    else:
        handle_local_query(query)


def run_cli(data_dir: str = "Archive") -> None:
    global CURRENT_MODE, AI_CONTEXT

    print("Loading archive and building index, please wait...")
    if os.path.exists(data_dir):
        manager.load_data(data_dir)
    else:
        print(f"Warning: Directory '{data_dir}' not found.")

    print("\n" + "=" * 60)
    print(" Sentence Autocomplete Engine (Part A + Part B Gemini)")
    print(" Commands:")
    print("   #         : Reset the current query session")
    print("   :ai       : Switch to Gemini Context-Aware AI mode")
    print("   :local    : Switch to Local Corpus search mode")
    print("   :context <name> : Set AI context (e.g. :context Technical)")
    print("   Ctrl+C    : Exit")
    print("=" * 60 + "\n")

    current_query = ""

    while True:
        try:
            mode_indicator = f"[{CURRENT_MODE.upper()}:{AI_CONTEXT}] " if CURRENT_MODE == "ai" else "[LOCAL] "
            prompt = f"{mode_indicator}{current_query}" if current_query else f"{mode_indicator}> "
            user_input = input(prompt)
        except (EOFError, KeyboardInterrupt):
            print("\nExiting...")
            break

        # Handle Commands
        stripped = user_input.strip()
        if stripped == ":ai":
            CURRENT_MODE = "ai"
            print(f">> Switched to AI Mode (Context: {AI_CONTEXT})")
            continue
        if stripped == ":local":
            CURRENT_MODE = "local"
            print(">> Switched to Local Corpus Mode")
            continue
        if stripped.startswith(":context"):
            parts = stripped.split(maxsplit=1)
            AI_CONTEXT = parts[1] if len(parts) > 1 else "General"
            print(f">> AI Context set to: {AI_CONTEXT}")
            continue

        if RESET_TOKEN in user_input:
            print("Session reset.")
            current_query = ""
            continue

        current_query += user_input

        if not current_query.strip():
            continue

        handle_query(current_query)


if __name__ == "__main__":
    run_cli()