"""Interactive CLI loop for Sentence Autocomplete & Hybrid AI Search Engine."""

import os
import sys
from types import SimpleNamespace
from typing import List, Optional

from core.models import AutoCompleteData
from core.normalizer import normalize_text
from core.indexer import DataManager
from core.scoring import rank_candidates
from core.snapshot_store import read_current_snapshot_id
from core.snapshot_watcher import SnapshotWatcher
import core.search_engine as search_engine

from services.gemini_service import GeminiService
from services.gemini_completion_service import GeminiCompletionService
from services.semantic_indexer import SemanticSearchEngine, SemanticMatchResult
from services.gemini_speech import GeminiSpeechTranscriber
from services.speech import VoiceInputError

RESET_TOKEN = "#"
SEMANTIC_PREFIX = "!s "
VOICE_PREFIX = "!v "
SNAPSHOTS_DIR_ENV = "BAT_SNAPSHOTS_DIR"

# Initialize core services
manager = DataManager()
gemini_service = GeminiService()
gemini_completion_service = GeminiCompletionService()
semantic_engine = SemanticSearchEngine(gemini_service)
speech_transcriber = GeminiSpeechTranscriber()

# Operating modes: 'local', 'semantic', 'ai'
CURRENT_MODE = "local"
AI_CONTEXT = "General"
SPEECH_LANG = "en-US"


def format_result(rank: int, result: AutoCompleteData) -> str:
    """Format lexical completion or AI completion result."""
    if result.source_text == "[Generated by Gemini]":
        return f"{rank}. {result.completed_sentence}  \033[94m[AI Generated: Gemini]\033[0m"
    return (
        f"{rank}. {result.completed_sentence}  "
        f"[source: {result.source_text}, line {result.offset}, score: {result.score}]"
    )


def format_semantic_result(rank: int, result: SemanticMatchResult) -> str:
    """Format semantic vector search result."""
    return (
        f"{rank}. {result.sentence}  "
        f"[source: {result.source_path}, line {result.line_number}, similarity: {result.similarity_score:.4f}]"
    )


def handle_local_query(query: str) -> None:
    """Handle standard Part A lexical matching from local corpus."""
    # ZDT: cheap on every query - if `manager` is a SnapshotWatcher and the
    # offline side has published a new snapshot since we last loaded, swap
    # it in now. If it hasn't changed, this is just one small file read.
    if hasattr(manager, "refresh"):
        manager.refresh()

    normalized_query = normalize_text(query)
    raw_matches = search_engine.search(query, manager) if hasattr(search_engine, "search") else []

    # Map MatchCandidate fields to what rank_candidates expects
    adapted_matches = [
        SimpleNamespace(
            sentence_id=m.sentence_id,
            error_type=None if m.edit_type == "exact" else m.edit_type,
            error_index=m.edit_position,
        )
        for m in raw_matches
    ]

    results = rank_candidates(normalized_query, adapted_matches, manager.get_sentence, top_k=5)

    if not results:
        print("No matching sentences found in corpus.")
        return

    for rank, result in enumerate(results, start=1):
        print(format_result(rank, result))


def handle_semantic_query(raw_query: str) -> None:
    """Handle Part B semantic vector search with cross-lingual translation."""
    clean_query = (
        raw_query[len(SEMANTIC_PREFIX) :].strip()
        if raw_query.startswith(SEMANTIC_PREFIX)
        else raw_query.strip()
    )

    if not clean_query:
        return

    if gemini_service.is_available() and not all(ord(c) < 128 for c in clean_query):
        translated = gemini_service.translate_to_english(clean_query)
        if translated != clean_query:
            print(f"\033[96m[Cross-Lingual Translated]: {translated}\033[0m")
            clean_query = translated

    results = semantic_engine.search(clean_query, top_k=5)

    if not results:
        print("No semantic matches found in cache.")
        return

    print("--- Semantic Search Results (Google Embeddings) ---")
    for rank, result in enumerate(results, start=1):
        print(format_semantic_result(rank, result))


def handle_ai_query(query: str) -> None:
    """Handle Part B generative completions using Gemini LLM."""
    try:
        results = gemini_completion_service.generate_completions(
            query, domain_context=AI_CONTEXT, top_k=5
        )
        if not results:
            print("No AI completions generated.")
            return

        print(f"--- AI Completions (Context: {AI_CONTEXT}) ---")
        for rank, result in enumerate(results, start=1):
            print(format_result(rank, result))
    except Exception as err:
        print(f"\033[91m[Gemini API Error: {err}]\033[0m")
        print("Falling back to standard local corpus search...")
        handle_local_query(query)


def handle_voice_transcribe(audio_path: str) -> Optional[str]:
    """Transcribe a WAV audio file via Gemini Speech."""
    if not os.path.exists(audio_path):
        print(f"\033[91m[Error]: Audio file '{audio_path}' not found.\033[0m")
        return None
    try:
        print(f"Transcribing '{audio_path}' ({SPEECH_LANG})...")
        transcription = speech_transcriber.transcribe(audio_path, language_code=SPEECH_LANG)
        print(f"\033[92m[Transcribed ({transcription.latency_seconds:.2f}s)]:\033[0m {transcription.text}")
        return transcription.text
    except VoiceInputError as exc:
        print(f"\033[91m[Voice Error]: {exc}\033[0m")
        return None


def handle_query(query: str) -> None:
    """Route query based on prefix or active mode."""
    if query.startswith(SEMANTIC_PREFIX):
        handle_semantic_query(query)
    elif CURRENT_MODE == "ai":
        handle_ai_query(query)
    elif CURRENT_MODE == "semantic":
        handle_semantic_query(query)
    else:
        handle_local_query(query)


def run_cli(data_dir: str = "Archive", snapshots_dir: Optional[str] = None) -> None:
    """Start the interactive loop.

    ZDT: if `snapshots_dir` (or the `BAT_SNAPSHOTS_DIR` env var) is set,
    lexical search is served from the snapshot published there instead of
    `data_dir`, and `manager` becomes a `SnapshotWatcher` that live-reloads
    whenever the offline side (`cli/build_snapshot.py`) publishes a new
    snapshot - no restart of this process required.
    """
    global CURRENT_MODE, AI_CONTEXT, SPEECH_LANG, manager

    snapshots_dir = snapshots_dir or os.getenv(SNAPSHOTS_DIR_ENV)

    print("Loading archive and initializing engines, please wait...")
    if snapshots_dir:
        if read_current_snapshot_id(snapshots_dir) is None:
            print(f"Warning: no published snapshot found in '{snapshots_dir}'.")
        else:
            manager = SnapshotWatcher(snapshots_dir)
            print(f"[ZDT] Serving snapshot '{manager.current_snapshot_id}' from '{snapshots_dir}'.")
    elif os.path.exists(data_dir) or os.path.exists(manager.cache_file):
        manager.load_data(data_dir)
        semantic_engine._load_from_cache()
    else:
        print(f"Warning: Directory '{data_dir}' not found.")

    print("\n" + "=" * 65)
    print(" 🚀 Hybrid Sentence Autocomplete & AI Search Engine")
    print(" Commands & Modes:")
    print("   #                 : Reset query session")
    print("   !s <query>        : One-time Semantic search")
    print("   !v <wav_file>     : Transcribe audio file and execute search")
    print("   :semantic         : Switch default mode to Semantic Search")
    print("   :ai               : Switch default mode to Gemini AI Completions")
    print("   :local            : Switch default mode to Local Corpus search")
    print("   :context <name>   : Set AI context (e.g. :context Technical)")
    print("   :lang <code/he/en>: Set Speech language (e.g. :lang he-IL / en-US)")
    print("   Ctrl+C            : Exit")
    print("=" * 65 + "\n")

    current_query = ""

    while True:
        try:
            if CURRENT_MODE == "ai":
                mode_prefix = f"[AI:{AI_CONTEXT}] "
            elif CURRENT_MODE == "semantic":
                mode_prefix = "[SEMANTIC] "
            else:
                mode_prefix = "[LOCAL] "

            prompt = f"{mode_prefix}{current_query}" if current_query else f"{mode_prefix}> "
            user_input = input(prompt)
        except (EOFError, KeyboardInterrupt):
            print("\nExiting...")
            break

        stripped = user_input.strip()

        # Handle commands and mode switching
        if stripped == ":ai":
            CURRENT_MODE = "ai"
            print(f">> Switched to AI Generation Mode (Context: {AI_CONTEXT})")
            current_query = ""
            continue
        if stripped == ":semantic":
            CURRENT_MODE = "semantic"
            print(">> Switched to Semantic Vector Search Mode")
            current_query = ""
            continue
        if stripped == ":local":
            CURRENT_MODE = "local"
            print(">> Switched to Local Corpus Mode")
            current_query = ""
            continue
        if stripped.startswith(":context"):
            parts = stripped.split(maxsplit=1)
            AI_CONTEXT = parts[1] if len(parts) > 1 else "General"
            print(f">> AI Context set to: {AI_CONTEXT}")
            continue
        if stripped.startswith(":lang"):
            parts = stripped.split(maxsplit=1)
            SPEECH_LANG = parts[1] if len(parts) > 1 else "en-US"
            print(f">> Speech language set to: {SPEECH_LANG}")
            continue

        if stripped.startswith("!v "):
            audio_path = stripped[3:].strip()
            transcribed_text = handle_voice_transcribe(audio_path)
            if transcribed_text:
                handle_query(transcribed_text)
            current_query = ""
            continue

        if RESET_TOKEN in user_input:
            print("Session reset.")
            current_query = ""
            continue

        current_query += user_input

        if not current_query.strip():
            continue

        if current_query.startswith(SEMANTIC_PREFIX):
            handle_semantic_query(current_query)
            current_query = ""
        else:
            handle_query(current_query)


if __name__ == "__main__":
    run_cli()