"""Context-aware autocomplete service powered by Google Gemini REST API.

Uses Python standard library only (no external dependencies required).
"""

import json
import os
import urllib.error
import urllib.request
from typing import List, Optional

from core.models import AutoCompleteData


def _load_env_file(filepath: str = ".env") -> None:
    """Simple .env file loader for standard library."""
    if not os.path.exists(filepath):
        return
    try:
        with open(filepath, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith("#") or "=" not in line:
                    continue
                key, val = line.split("=", 1)
                key = key.strip()
                val = val.strip().strip("\"'")
                if key and key not in os.environ:
                    os.environ[key] = val
    except Exception:
        pass


_load_env_file()


class GeminiCompletionService:
    """Service to generate context-aware sentence completions via Gemini REST API."""

    def __init__(self, api_key: Optional[str] = None, model_name: str = "gemini-2.5-flash"):
        self.api_key = api_key or os.getenv("GEMINI_API_KEY")
        self.model_name = model_name

    def _get_api_key(self) -> str:
        key = self.api_key or os.getenv("GEMINI_API_KEY")
        if not key:
            raise ValueError("GEMINI_API_KEY is not set in environment or .env file.")
        return key

    def generate_completions(
        self,
        query: str,
        domain_context: str = "General",
        top_k: int = 5,
    ) -> List[AutoCompleteData]:
        """Generates contextual sentence completions using Gemini REST endpoint."""
        if not query or not query.strip():
            return []

        api_key = self._get_api_key()
        url = (
            f"https://generativelanguage.googleapis.com/v1beta/models/"
            f"{self.model_name}:generateContent?key={api_key}"
        )

        prompt = (
            f"You are an intelligent sentence auto-completion assistant.\n"
            f"The user is typing: \"{query}\"\n"
            f"Context/Domain: {domain_context}\n\n"
            f"Provide up to {top_k} natural, high-quality full sentences that begin with or logically "
            f"complete the user's input.\n"
            f"Return the response strictly as a JSON array of strings (e.g. [\"sentence 1\", \"sentence 2\"]), "
            f"with no markdown blocks and no extra text."
        )

        payload = {
            "contents": [{"parts": [{"text": prompt}]}],
            "generationConfig": {
                "temperature": 0.7,
                "responseMimeType": "application/json",
            },
        }

        data = json.dumps(payload).encode("utf-8")
        req = urllib.request.Request(
            url,
            data=data,
            headers={"Content-Type": "application/json"},
            method="POST",
        )

        try:
            with urllib.request.urlopen(req, timeout=10) as response:
                res_body = response.read().decode("utf-8")
                res_json = json.loads(res_body)
        except urllib.error.HTTPError as err:
            error_details = err.read().decode("utf-8", errors="ignore")
            raise RuntimeError(f"HTTP {err.code}: {error_details}")
        except urllib.error.URLError as err:
            raise RuntimeError(f"Network error connecting to Gemini API: {err.reason}")

        try:
            candidates = res_json.get("candidates", [])
            if not candidates:
                return []
            raw_text = candidates[0]["content"]["parts"][0]["text"]
            completions = json.loads(raw_text)
            if not isinstance(completions, list):
                completions = []
        except (KeyError, IndexError, json.JSONDecodeError):
            completions = []

        results: List[AutoCompleteData] = []
        for text in completions[:top_k]:
            if not text:
                continue
            results.append(
                AutoCompleteData(
                    completed_sentence=str(text),
                    source_text="[Generated by Gemini]",
                    offset=0,
                    score=0,
                )
            )

        return results