"""Context-aware autocomplete service powered by Google Gemini API."""

import json
import os
import urllib.error
import urllib.request
from typing import List, Optional

from core.models import AutoCompleteData

try:
    from google import genai
except ImportError:
    genai = None

# המודל המעודכן לפי הוראת ה-API
DEFAULT_MODEL = "gemini-3.6-flash"


def _load_env_file(filepath: str = ".env") -> None:
    if not os.path.exists(filepath):
        return
    try:
        with open(filepath, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith("#") or "=" not in line:
                    continue
                key, val = line.split("=", 1)
                key = key.strip()
                val = val.strip().strip("\"'")
                if key and key not in os.environ:
                    os.environ[key] = val
    except Exception:
        pass


_load_env_file()


class GeminiCompletionService:
    """Service to generate context-aware sentence completions via Gemini."""

    def __init__(self, api_key: Optional[str] = None, model_name: str = DEFAULT_MODEL):
        self.api_key = api_key or os.getenv("GEMINI_API_KEY")
        self.model_name = model_name
        self.client = None

        if self.api_key and genai:
            try:
                self.client = genai.Client(api_key=self.api_key)
            except Exception as e:
                print(f"[Warning] Gemini SDK init failed in completion service: {e}")

    def generate_completions(
        self,
        query: str,
        domain_context: str = "General",
        top_k: int = 5,
    ) -> List[AutoCompleteData]:
        if not query or not query.strip():
            return []

        prompt = (
            f"You are an intelligent sentence auto-completion assistant.\n"
            f"The user is typing: \"{query}\"\n"
            f"Context/Domain: {domain_context}\n\n"
            f"Provide up to {top_k} natural, high-quality full sentences that begin with or logically "
            f"complete the user's input.\n"
            f"Return the response strictly as a JSON array of strings (e.g. [\"sentence 1\", \"sentence 2\"]), "
            f"with no markdown formatting, no code blocks, and no extra text."
        )

        completions: List[str] = []

        if self.client:
            try:
                response = self.client.models.generate_content(
                    model=self.model_name,
                    contents=prompt,
                )
                if response and response.text:
                    raw_text = response.text.strip()
                    if raw_text.startswith("```json"):
                        raw_text = raw_text.removeprefix("```json").removesuffix("```").strip()
                    elif raw_text.startswith("```"):
                        raw_text = raw_text.removeprefix("```").removesuffix("```").strip()
                    parsed = json.loads(raw_text)
                    if isinstance(parsed, list):
                        completions = parsed
            except Exception as e:
                print(f"[GeminiCompletion SDK Error]: {e}")

        if not completions and self.api_key:
            completions = self._generate_via_rest(prompt)

        results: List[AutoCompleteData] = []
        for text in completions[:top_k]:
            if not text:
                continue
            results.append(
                AutoCompleteData(
                    completed_sentence=str(text),
                    source_text="[Generated by Gemini]",
                    offset=0,
                    score=0,
                )
            )

        return results

    def _generate_via_rest(self, prompt: str) -> List[str]:
        url = (
            f"https://generativelanguage.googleapis.com/v1beta/models/"
            f"{self.model_name}:generateContent?key={self.api_key}"
        )
        payload = {
            "contents": [{"parts": [{"text": prompt}]}],
            "generationConfig": {
                "temperature": 0.7,
                "responseMimeType": "application/json",
            },
        }

        try:
            req = urllib.request.Request(
                url,
                data=json.dumps(payload).encode("utf-8"),
                headers={"Content-Type": "application/json"},
                method="POST",
            )
            with urllib.request.urlopen(req, timeout=10) as response:
                res_json = json.loads(response.read().decode("utf-8"))

            candidates = res_json.get("candidates", [])
            if not candidates:
                return []
            raw_text = candidates[0]["content"]["parts"][0]["text"]
            data = json.loads(raw_text)
            return data if isinstance(data, list) else []
        except Exception as e:
            print(f"[GeminiCompletion REST Error]: {e}")
            return []